  # Configurations for the exploration pipeline.
  # For more details, please check comments in the params.h file and the wiki.
  #-------------------------------------------------------------------------------
  # ROBOT CONFIGURATION
  #-------------------------------------------------------------------------------
RobotParams:
  type:               kAerialRobot
  size:               [0.4, 0.4, 0.4] # Actual size of the robot in meters [x, y, z]
  size_extension_min: [0.0, 0.0, 0.0] # minimum extension outside of robot size allowed to operate
  size_extension:     [0.0, 0.0, 0.0] # maximum extension outside of the robot size
  center_offset:      [-0.0, 0.0, 0.0]
  relax_ratio:        0.5 # Used to define an intermediate size between size_extension_min and size_extension for planning
  bound_mode:         kExtendedBound
  safety_extension:   [0.5, 0.5, 0.5] # Safety extension outside the bounding box of a path segment used to improve it by pushing it away from obstacles
#-------------------------------------------------------------------------------
# SENSOR CONFIGURATION
#  sensor_list: Define a set of sensors relevant to the exploration task.
#  rotations: ZYX order;
#             all follows ROS convention (X-forward, Y-left, Z-Up).
#-------------------------------------------------------------------------------
SensorParams:
  sensor_list:      ["OS064", "CamF", "Cam", "CamExp"]
  OS064:
    type:           kLidar
    max_range:      1.0
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(2*pi), rad(90*pi/180)]
    resolution:     [rad(10.0*pi/180), rad(10.0*pi/180)]
    frontier_percentage_threshold: 0.005
  CamF:
    type:           kLidar
    CameraType:     kFixed
    rot_lims:       [0.0, 0.0]
    max_range:      3.5
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(100*pi/180), rad(60*pi/180)]
    resolution:     [rad(4.0*pi/180), rad(4.0*pi/180)]
    frontier_percentage_threshold: 0.01
  Cam:
    type:           kLidar
    CameraType:     kRotating
    rot_lims:       [rad(-80*pi/180.0), rad(80*pi/180.0)]
    max_range:      2.0 #2.5
    min_range:      0.25
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(80*pi/180.0), rad(60*pi/180.0)]
    resolution:     [rad(5.0*pi/180), rad(5.0*pi/180)]
    frontier_percentage_threshold: 0.06
  CamExp:
    type:           kLidar
    CameraType:     kRotating
    rot_lims:       [-1.57, 1.57]
    max_range:      5.0
    min_range:      0.25
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(84*pi/180.0), rad(64*pi/180.0)]
    resolution:     [rad(7.0*pi/180), rad(7.0*pi/180)]
    frontier_percentage_threshold: 0.06

CameraAnnotationParams:
  sensor_list:      ["Cam"]
  Cam:
    type:           kLidar
    rot_lims:       [-1.55, 1.55]
    max_range:      2.0 #2.5
    center_offset:  [0.0, 0.0, 0.0]
    rotations:      [0.0, 0.0, 0.0]
    fov:            [rad(84*pi/180.0), rad(64*pi/180.0)]
    resolution:     [rad(2.0*pi/180), rad(2.0*pi/180)]
    frontier_percentage_threshold: 0.01
#-------------------------------------------------------------------------------
# SAMPLING SPACE CONFIGURATION
#   Global: Strictly defined bounds for the whole environment.
#   Local: Define a local space wrt current robot state for planning.
#-------------------------------------------------------------------------------
BoundedSpaceParams:
  Global:
    type:           kCuboid
    min_val:        [-60.0, -101.0, -0.5]
    max_val:        [60.0, 100.0, 11.0]
  Local:
    type:           kCuboid
    min_val:        [-10.0, -10.0, -10.0]
    max_val:        [10.0, 10.0, 10.0]
    min_extension:  [-20.0, -20.0, -20.0]
    max_extension:  [20.0, 20.0, 20.0]
  LocalSearch:
    type:           kCuboid
    min_val:        [-50.0, -50.0, -1.0]
    max_val:        [50.0, 50.0, 1.0]
  # Adaptive OBB:
  LocalAdaptiveExp:
    type:           kCuboid
    min_val:        [-10.0, -10.0, -0.75]
    max_val:        [10.0, 10.0, 0.75]
NoGainZones:
  g1:  # Back
    type:           kCuboid
    min_val:        [-50.0, -10.0, -10.0]
    max_val:        [2.0, 10.0, 10.0]
#-------------------------------------------------------------------------------
# SAMPLING POLICY CONFIGURATION
#   Sample space limited to 4 states: X, Y, Z, and Heading
#-------------------------------------------------------------------------------
RandomSamplerParams:
  SamplerForExploration:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi/2)
      max_val:        rad(pi/2)
  SamplerForSearching:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi/2)
      max_val:        rad(pi/2)
  SamplerForAdaptiveExp:
    X:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Y:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Z:
      pdf_type:       kUniform
      sample_mode:    kLocal
    Heading:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi)
      max_val:        rad(pi)
    Pitch:
      pdf_type:       kUniform
      sample_mode:    kManual
      min_val:        rad(-pi/2)
      max_val:        rad(pi/2)

#-------------------------------------------------------------------------------
# EXPLORATION CONFIGURATION
# exp_sensor_list: sensors used to compute exploration gain.
#-------------------------------------------------------------------------------
PlanningParams:
  type:             kBasicExploration #kAdaptiveExploration, kBasicExploration
  rr_mode:          kGraph
  graph_building_mode: kBatch
  exp_sensor_list:  ["OS064"]
  inspection_sensor_list:  ["CamF"]
  v_max:            1.0 # max velocity m/s
  v_homing_max:     0.9 # max velocity m/s
  yaw_rate_max:     0.9 # max angular velocity rad/s
  yaw_tangent_correction: false # If true - all headings will be along the path segment
  edge_length_min:  0.2
  edge_length_max:  3.0
  edge_overshoot:   0.0 # m - Account for possible tracking error by collision checking on an extended edge
  num_vertices_max: 400 # 400 # graph building stops if these many vertices are added 
  num_edges_max:    7000 # graph building stops if these many edges are added
  num_loops_cutoff: 2000 # Maximum iterations in which no vertices or edges are added to the graph
  num_loops_max:    7000 # Maximum iterations possible for graph building
  nearest_range:    3.0 # The max range within which a new vertex can be connected to an existing vertex
  nearest_range_min: 0.2 # >= edge_length_min
  nearest_range_max: 3.0 # <= edge_length_max
  use_current_state: true # If true, it will use the current state to plan from instead of the state provided by the PCI in the service call
  use_ray_model_for_volumetric_gain: true # if false, will check voxel by voxel in the sensor frustum 
  exp_gain_voxel_size: 0.8 # used if use_ray_model_for_volumetric_gain is false
  # Gains:
  path_length_penalty: 0.01 # 0.4
  path_direction_penalty: 0.02 # 0.01
  occupied_voxel_gain: 0.0
  free_voxel_gain:  0.0 # prefer directions towards more free voxels in case of the dead-end
  unknown_voxel_gain: 60.0

  traverse_length_max: 5.0 # Maximum length of the best path will be truncated to for actual traversal
  traverse_time_max: 500.0
  path_safety_enhance_enable: false
  augment_free_voxels_time: 3
  free_frustum_before_planning: false
  freespace_cloud_enable: false
  leafs_only_for_volumetric_gain: true # Whether to calculate gain of the entire path or only the leaf nodes
  cluster_vertices_for_gain: false
  clustering_radius: 0.5
  path_interpolation_distance: -1.0 # 0.5
  
  time_budget_limit: 1000 # seconds
  auto_homing_enable: false
  go_home_if_fully_explored: false

  nonuniform_ray_cast: false
  ray_cast_step_size_multiplier: 1.0

  use_camera_gain: false
  annotate_map_with_camera: true
  
  inspection_planning: false

  keep_leaf_yaw_only: true

  enable_opening_traversal: false
  opening_alignment_z_offset: 0.0 # -0.25
  only_opening_traversal: false

  auto_opening_path_approval: true
  max_opening_height: 20.0

  box_check_method: 0
  line_check_method: 1

  add_only_frontiers_to_global_graph: false

  min_coverage_percentage: 0.9
  inspection_xy_spacing: 1.5 # 1.5
  inspection_z_spacing: 0.75 # 2.0
  inspection_thr_esdf_dist: 0.75 # 1.5
  inspection_target_viewing_range: 1.5 #1.5 # 2.5
  inspection_graph_vertices: 500
  max_inspection_vertices: 100
  #: 10

  max_surface_distance: 1.5
  limit_vertices_to_surface: false
  min_occ_surface: 0.0

  max_exploration_iterations: 5
  exploration_only: false

  compartment_centers: [0.0, -5.0, 5.0]
  compartment_dimensions:
    type:           kCuboid
    min_val:        [-7.0, -7.0, -6.0]
    max_val:        [7.0, 7.0, 6.0]

  geofence_checking_enable: true

AdaptiveObbParams:
  type: kPca
  local_pointcloud_range: 50.0
  bounding_box_size_max: 35